import { EmbedBuilder, SlashCommandBuilder } from 'discord.js';

/**
 * /verify command used to link a Discord user to their Nexus AMS account.
 * Accepts a verification code generated by Nexus and forwards Discord identity metadata.
 */
export const data = new SlashCommandBuilder()
  .setName('verify')
  .setDescription('Link your Discord account to your Nexus AMS account using a verification code.')
  .addStringOption((option) =>
    option
      .setName('code')
      .setDescription('Verification code provided by Nexus AMS.')
      .setRequired(true),
  )
  .setDMPermission(false);

/**
 * Execute handler for /verify.
 * Collects Discord identity details, validates the provided code, calls Nexus, and responds with embeds.
 * @param {import('discord.js').ChatInputCommandInteraction} interaction incoming command interaction
 * @param {{ logger: import('../services/Logger.js').Logger, apiService: import('../services/ApiService.js').ApiService }} context shared dependencies injected by the bot bootstrapper
 */
export const execute = async (interaction, { logger, apiService }) => {
  const user = interaction.user;

  const logContext = {
    command: 'verify',
    userId: user.id,
    username: user.username,
    guildId: interaction.guildId,
  };

  try {
    // Validate dependencies early to avoid confusing runtime failures if wiring breaks.
    if (!apiService) {
      logger.error('ApiService is not available to /verify command', logContext);
      await interaction.reply({
        content: 'Verification service is unavailable. Please try again later.',
        ephemeral: false,
      });
      return;
    }

    const rawCode = interaction.options.getString('code', true);
    const verificationCode = rawCode.trim();

    // Thorough input validation with user-friendly feedback.
    if (!verificationCode) {
      await interaction.reply({
        embeds: [buildErrorEmbed('Please provide the verification code you received from Nexus AMS.')],
        ephemeral: false,
      });
      return;
    }

    if (verificationCode.length < 4) {
      await interaction.reply({
        embeds: [buildErrorEmbed('That code looks too short. Please copy the full code from Nexus AMS.')],
        ephemeral: false,
      });
      return;
    }

    if (verificationCode.length > 128) {
      await interaction.reply({
        embeds: [buildErrorEmbed('That code looks too long. Please double-check and try again.')],
        ephemeral: false,
      });
      return;
    }

    if (/\s/.test(verificationCode)) {
      await interaction.reply({
        embeds: [buildErrorEmbed('Verification codes should not contain spaces. Please try again without spaces.')],
        ephemeral: false,
      });
      return;
    }

    // Collect Discord metadata for auditing/traceability.
    const discriminator = user.discriminator && user.discriminator !== '0' ? user.discriminator : null;
    const avatarUrl = user.displayAvatarURL({ size: 512, extension: 'png' });
    const discordIdentity = {
      id: user.id,
      username: user.username,
      globalName: user.globalName ?? null,
      discriminator,
      avatarUrl,
      tag: discriminator ? `${user.username}#${discriminator}` : user.username,
    };

    const payload = {
      token: verificationCode,
      discord_id: discordIdentity.id,
      discord_username: discordIdentity.username,
      discord_global_name: discordIdentity.globalName ?? undefined,
      discord_discriminator: discordIdentity.discriminator ?? undefined,
      discord_avatar: discordIdentity.avatarUrl,
      metadata: {
        command: 'verify',
        discord_tag: discordIdentity.tag,
        issued_at: new Date().toISOString(),
      },
    };

    logger.info('Processing /verify command', logContext);

    // Defer to give Nexus time to respond without hitting Discord interaction timeouts.
    await interaction.deferReply({ ephemeral: false });

    const apiResult = await apiService.verifyUser(payload);

    if (apiResult?.success) {
      const nexusUsername =
        apiResult.data?.username ??
        apiResult.data?.nexusUsername ??
        apiResult.data?.user?.username ??
        'Nexus user';

      const confirmationDetail =
        apiResult.data?.message ??
        apiResult.data?.detail ??
        'Your Discord account is now linked to Nexus AMS.';

      const successEmbed = new EmbedBuilder()
        .setTitle('Verification Successful')
        .setColor(0x57f287)
        .setDescription(confirmationDetail)
        .addFields(
          { name: 'Nexus Account', value: `\`${nexusUsername}\``, inline: true },
          { name: 'Discord', value: discordIdentity.tag, inline: true },
        )
        .setThumbnail(discordIdentity.avatarUrl)
        .setTimestamp();

      await interaction.editReply({ embeds: [successEmbed] });
      return;
    }

    const errorMessage =
      apiResult?.message ??
      'Verification failed. Please confirm your code and try again or request a new one.';

    const errorEmbed = new EmbedBuilder()
      .setTitle('Verification Failed')
      .setColor(0xed4245)
      .setDescription(errorMessage)
      .addFields({ name: 'Need help?', value: 'If the issue persists, request a new code or contact an administrator.' })
      .setTimestamp();

    await interaction.editReply({ embeds: [errorEmbed] });
  } catch (error) {
    logger.error('Unhandled error while executing /verify', { ...logContext, error: error?.message ?? error });

    const fallbackEmbed = new EmbedBuilder()
      .setTitle('Verification Error')
      .setColor(0xed4245)
      .setDescription('Something went wrong while processing your verification. Please try again shortly.')
      .setTimestamp();

    if (interaction.deferred || interaction.replied) {
      await interaction.followUp({ embeds: [fallbackEmbed], ephemeral: false }).catch(() => {});
    } else {
      await interaction.reply({ embeds: [fallbackEmbed], ephemeral: false }).catch(() => {});
    }
  }
};

/**
 * Helper to build consistently styled error embeds for validation failures.
 * @param {string} message user-facing error message
 * @returns {import('discord.js').EmbedBuilder}
 */
function buildErrorEmbed(message) {
  return new EmbedBuilder()
    .setTitle('Verification Issue')
    .setColor(0xed4245)
    .setDescription(message)
    .setTimestamp();
}
